//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Diagnostics;
using System.Web.Services;
using System.Web.Services.Protocols;
using System.Xml.Serialization;

// 
// This source code was auto-generated by wsdl, Version=4.6.1055.0.
// 


/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Web.Services.WebServiceBindingAttribute(Name="GetRoutingDataServicesPortBinding", Namespace="http://getroutingdata.wsbeans.iseries/")]
public partial class GetRoutingData : System.Web.Services.Protocols.SoapHttpClientProtocol {
    
    private System.Threading.SendOrPostCallback getrtedtaOperationCompleted;
    
    /// <remarks/>
    public GetRoutingData() {
        this.Url = "http://10.0.0.15:10060/web/services/GetRoutingDataService/GetRoutingData";
    }
    
    /// <remarks/>
    public event getrtedtaCompletedEventHandler getrtedtaCompleted;
    
    /// <remarks/>
    [System.Web.Services.Protocols.SoapDocumentMethodAttribute("", RequestNamespace="http://getroutingdata.wsbeans.iseries/", ResponseNamespace="http://getroutingdata.wsbeans.iseries/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
    [return: System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public getrtedtaResult getrtedta([System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)] getrtedtaInput arg0) {
        object[] results = this.Invoke("getrtedta", new object[] {
                    arg0});
        return ((getrtedtaResult)(results[0]));
    }
    
    /// <remarks/>
    public System.IAsyncResult Begingetrtedta(getrtedtaInput arg0, System.AsyncCallback callback, object asyncState) {
        return this.BeginInvoke("getrtedta", new object[] {
                    arg0}, callback, asyncState);
    }
    
    /// <remarks/>
    public getrtedtaResult Endgetrtedta(System.IAsyncResult asyncResult) {
        object[] results = this.EndInvoke(asyncResult);
        return ((getrtedtaResult)(results[0]));
    }
    
    /// <remarks/>
    public void getrtedtaAsync(getrtedtaInput arg0) {
        this.getrtedtaAsync(arg0, null);
    }
    
    /// <remarks/>
    public void getrtedtaAsync(getrtedtaInput arg0, object userState) {
        if ((this.getrtedtaOperationCompleted == null)) {
            this.getrtedtaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetrtedtaOperationCompleted);
        }
        this.InvokeAsync("getrtedta", new object[] {
                    arg0}, this.getrtedtaOperationCompleted, userState);
    }
    
    private void OngetrtedtaOperationCompleted(object arg) {
        if ((this.getrtedtaCompleted != null)) {
            System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
            this.getrtedtaCompleted(this, new getrtedtaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
        }
    }
    
    /// <remarks/>
    public new void CancelAsync(object userState) {
        base.CancelAsync(userState);
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getroutingdata.wsbeans.iseries/")]
public partial class getrtedtaInput {
    
    private getrouterequestds p_REQUESTField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public getrouterequestds P_REQUEST {
        get {
            return this.p_REQUESTField;
        }
        set {
            this.p_REQUESTField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getroutingdata.wsbeans.iseries/")]
public partial class getrouterequestds {
    
    private string wAREHOUSEIDField;
    
    private decimal dELIVERYDATEField;
    
    private string wAVEIDField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WAREHOUSEID {
        get {
            return this.wAREHOUSEIDField;
        }
        set {
            this.wAREHOUSEIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal DELIVERYDATE {
        get {
            return this.dELIVERYDATEField;
        }
        set {
            this.dELIVERYDATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string WAVEID {
        get {
            return this.wAVEIDField;
        }
        set {
            this.wAVEIDField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getroutingdata.wsbeans.iseries/")]
public partial class customT {
    
    private string dELIVERYRESTRICTIONField;
    
    private string bACKORDERField;
    
    private string zONEField;
    
    private decimal zONEDATEField;
    
    private decimal zONEPOSITIONField;
    
    private string zONEFOLDERField;
    
    private string xZONEField;
    
    private decimal xPOSITIONField;
    
    private decimal xTRANSFERTIMEField;
    
    private decimal tIMEWINDOWSTARTField;
    
    private decimal tIMEWINDOWENDField;
    
    private decimal mINUTESATSTOPField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string DELIVERYRESTRICTION {
        get {
            return this.dELIVERYRESTRICTIONField;
        }
        set {
            this.dELIVERYRESTRICTIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BACKORDER {
        get {
            return this.bACKORDERField;
        }
        set {
            this.bACKORDERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZONE {
        get {
            return this.zONEField;
        }
        set {
            this.zONEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal ZONEDATE {
        get {
            return this.zONEDATEField;
        }
        set {
            this.zONEDATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal ZONEPOSITION {
        get {
            return this.zONEPOSITIONField;
        }
        set {
            this.zONEPOSITIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZONEFOLDER {
        get {
            return this.zONEFOLDERField;
        }
        set {
            this.zONEFOLDERField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string XZONE {
        get {
            return this.xZONEField;
        }
        set {
            this.xZONEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal XPOSITION {
        get {
            return this.xPOSITIONField;
        }
        set {
            this.xPOSITIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal XTRANSFERTIME {
        get {
            return this.xTRANSFERTIMEField;
        }
        set {
            this.xTRANSFERTIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal TIMEWINDOWSTART {
        get {
            return this.tIMEWINDOWSTARTField;
        }
        set {
            this.tIMEWINDOWSTARTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal TIMEWINDOWEND {
        get {
            return this.tIMEWINDOWENDField;
        }
        set {
            this.tIMEWINDOWENDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal MINUTESATSTOP {
        get {
            return this.mINUTESATSTOPField;
        }
        set {
            this.mINUTESATSTOPField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getroutingdata.wsbeans.iseries/")]
public partial class commentT {
    
    private string cOMMENT1Field;
    
    private string cOMMENT2Field;
    
    private string cOMMENT3Field;
    
    private string cOMMENT4Field;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COMMENT1 {
        get {
            return this.cOMMENT1Field;
        }
        set {
            this.cOMMENT1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COMMENT2 {
        get {
            return this.cOMMENT2Field;
        }
        set {
            this.cOMMENT2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COMMENT3 {
        get {
            return this.cOMMENT3Field;
        }
        set {
            this.cOMMENT3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string COMMENT4 {
        get {
            return this.cOMMENT4Field;
        }
        set {
            this.cOMMENT4Field = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getroutingdata.wsbeans.iseries/")]
public partial class orderT {
    
    private string uNIQUEORDERIDField;
    
    private decimal iNVOICEField;
    
    private decimal sTOREField;
    
    private decimal iNVOICEDATEField;
    
    private decimal iNVOICETYPEField;
    
    private decimal dELIVERYWEIGHTField;
    
    private decimal dELIVERYCUBESField;
    
    private decimal pICKUPWEIGHTField;
    
    private decimal pICKUPCUBESField;
    
    private decimal sALESMANField;
    
    private string sTOCKDISPOSITIONField;
    
    private string hASBACKORDERSField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string UNIQUEORDERID {
        get {
            return this.uNIQUEORDERIDField;
        }
        set {
            this.uNIQUEORDERIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal INVOICE {
        get {
            return this.iNVOICEField;
        }
        set {
            this.iNVOICEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal STORE {
        get {
            return this.sTOREField;
        }
        set {
            this.sTOREField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal INVOICEDATE {
        get {
            return this.iNVOICEDATEField;
        }
        set {
            this.iNVOICEDATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal INVOICETYPE {
        get {
            return this.iNVOICETYPEField;
        }
        set {
            this.iNVOICETYPEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal DELIVERYWEIGHT {
        get {
            return this.dELIVERYWEIGHTField;
        }
        set {
            this.dELIVERYWEIGHTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal DELIVERYCUBES {
        get {
            return this.dELIVERYCUBESField;
        }
        set {
            this.dELIVERYCUBESField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal PICKUPWEIGHT {
        get {
            return this.pICKUPWEIGHTField;
        }
        set {
            this.pICKUPWEIGHTField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal PICKUPCUBES {
        get {
            return this.pICKUPCUBESField;
        }
        set {
            this.pICKUPCUBESField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal SALESMAN {
        get {
            return this.sALESMANField;
        }
        set {
            this.sALESMANField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string STOCKDISPOSITION {
        get {
            return this.sTOCKDISPOSITIONField;
        }
        set {
            this.sTOCKDISPOSITIONField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string HASBACKORDERS {
        get {
            return this.hASBACKORDERSField;
        }
        set {
            this.hASBACKORDERSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getroutingdata.wsbeans.iseries/")]
public partial class customerT {
    
    private int cUSTOMERIDField;
    
    private string fIRSTNAMEField;
    
    private string lASTNAMEField;
    
    private string eMAILField;
    
    private string pHONE1Field;
    
    private string pHONE2Field;
    
    private string pHONE3Field;
    
    private string aDDRESS1Field;
    
    private string aDDRESS2Field;
    
    private string cITYField;
    
    private string sTATEField;
    
    private string zIP5Field;
    
    private string zIP4Field;
    
    private string gEOCODEXField;
    
    private string gEOCODEYField;
    
    private string cROSSSTREETField;
    
    private orderT[] oRDERSField;
    
    private decimal sERVICETIMEField;
    
    private commentT cOMMENTSField;
    
    private customT cUSTOMField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public int CUSTOMERID {
        get {
            return this.cUSTOMERIDField;
        }
        set {
            this.cUSTOMERIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string FIRSTNAME {
        get {
            return this.fIRSTNAMEField;
        }
        set {
            this.fIRSTNAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string LASTNAME {
        get {
            return this.lASTNAMEField;
        }
        set {
            this.lASTNAMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string EMAIL {
        get {
            return this.eMAILField;
        }
        set {
            this.eMAILField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PHONE1 {
        get {
            return this.pHONE1Field;
        }
        set {
            this.pHONE1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PHONE2 {
        get {
            return this.pHONE2Field;
        }
        set {
            this.pHONE2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string PHONE3 {
        get {
            return this.pHONE3Field;
        }
        set {
            this.pHONE3Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ADDRESS1 {
        get {
            return this.aDDRESS1Field;
        }
        set {
            this.aDDRESS1Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ADDRESS2 {
        get {
            return this.aDDRESS2Field;
        }
        set {
            this.aDDRESS2Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CITY {
        get {
            return this.cITYField;
        }
        set {
            this.cITYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string STATE {
        get {
            return this.sTATEField;
        }
        set {
            this.sTATEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZIP5 {
        get {
            return this.zIP5Field;
        }
        set {
            this.zIP5Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string ZIP4 {
        get {
            return this.zIP4Field;
        }
        set {
            this.zIP4Field = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GEOCODEX {
        get {
            return this.gEOCODEXField;
        }
        set {
            this.gEOCODEXField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string GEOCODEY {
        get {
            return this.gEOCODEYField;
        }
        set {
            this.gEOCODEYField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string CROSSSTREET {
        get {
            return this.cROSSSTREETField;
        }
        set {
            this.cROSSSTREETField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("ORDERS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public orderT[] ORDERS {
        get {
            return this.oRDERSField;
        }
        set {
            this.oRDERSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public decimal SERVICETIME {
        get {
            return this.sERVICETIMEField;
        }
        set {
            this.sERVICETIMEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public commentT COMMENTS {
        get {
            return this.cOMMENTSField;
        }
        set {
            this.cOMMENTSField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public customT CUSTOM {
        get {
            return this.cUSTOMField;
        }
        set {
            this.cUSTOMField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getroutingdata.wsbeans.iseries/")]
public partial class getrouteresponseds {
    
    private string sUCCESSFULField;
    
    private string bATCHIDField;
    
    private string mESSAGEField;
    
    private customerT[] cUSTOMERSField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string SUCCESSFUL {
        get {
            return this.sUCCESSFULField;
        }
        set {
            this.sUCCESSFULField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string BATCHID {
        get {
            return this.bATCHIDField;
        }
        set {
            this.bATCHIDField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public string MESSAGE {
        get {
            return this.mESSAGEField;
        }
        set {
            this.mESSAGEField = value;
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute("CUSTOMERS", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public customerT[] CUSTOMERS {
        get {
            return this.cUSTOMERSField;
        }
        set {
            this.cUSTOMERSField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.SerializableAttribute()]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
[System.Xml.Serialization.XmlTypeAttribute(Namespace="http://getroutingdata.wsbeans.iseries/")]
public partial class getrtedtaResult {
    
    private getrouteresponseds p_RESPONSEField;
    
    /// <remarks/>
    [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
    public getrouteresponseds P_RESPONSE {
        get {
            return this.p_RESPONSEField;
        }
        set {
            this.p_RESPONSEField = value;
        }
    }
}

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
public delegate void getrtedtaCompletedEventHandler(object sender, getrtedtaCompletedEventArgs e);

/// <remarks/>
[System.CodeDom.Compiler.GeneratedCodeAttribute("wsdl", "4.6.1055.0")]
[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.ComponentModel.DesignerCategoryAttribute("code")]
public partial class getrtedtaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
    
    private object[] results;
    
    internal getrtedtaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
            base(exception, cancelled, userState) {
        this.results = results;
    }
    
    /// <remarks/>
    public getrtedtaResult Result {
        get {
            this.RaiseExceptionIfNecessary();
            return ((getrtedtaResult)(this.results[0]));
        }
    }
}
